server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=GMT%2B8&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
  alarm:
#    mail:
#      enabled: true
#      smtpHost: pop.163.com
#      smtpPort: 22
#      to: 1553279148@qq.com
#      from: wlian19941025@163.com
#      username: wlian19941025@163.com
#      password: GAZRITPAJLPRNJZI
    template:
      # 开启通过模板配置
      enabled: true
      # 配置模板来源为文件
      source: FILE
      # 配置模板数据
      templates:
        errorTemp:
          templateId: errorTemp
          templateName: 服务异常模板
          templateContent: 这里是配置模板的内容  

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.example.springboot1
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
    cache-enabled: false

# 自定义redis key
#redis:
#  key:
#    prefix:
#      authCode: "portal:authCode:"
#    expire:
#      authCode: 120 # 验证码超期时间

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头